name: Style Checker

on: push
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Python style check
        uses: andymckay/pycodestyle-action@0.1.3

  laravel-pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Composer Install
        run: composer install

      - name: Run Laravel Pint
        run: ./vendor/bin/pint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Laravel Pint changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
